# Site settings
title: Nils Duran
author: Nils Duran
description: "AI Developer Portfolio"
baseurl: ""
url: "https://nilsduran.github.io"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Optional features
show_related_posts: False
show_post_footers: False
show_subscribe_cta: False
show_social_icons: false
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: true

# Social icons
github_username: nilsduran
linkedin_username: nils-duran2004

text:
  post:
    updated: "Updated"
    minute_read: '🕒 minuts'
    related_posts: "També et pot interessar"
  index:
    coming_soon: "Coming soon..."

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "with_toc_data", "footnotes"]
permalink: pretty
sass:
  compressed: true
plugins:
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
